import { api, request } from './contract.js';
const content=document.querySelector('#content'),title=document.querySelector('#title'),connection=document.querySelector('#connection');
let token=sessionStorage.getItem('ecs-token')||'';
const labels={overview:'Operations overview',devices:'Shuttle devices',tasks:'Task queue',alerts:'Alert monitor',settings:'Connection'};
function value(data, keys, fallback='—'){for(const key of keys){if(data?.[key]!==undefined)return data[key]}return fallback}
function card(label,metric,detail=''){return `<article class="card"><div class="label">${label}</div><div class="metric">${metric}</div><div class="label">${detail}</div></article>`}
async function overview(){content.innerHTML=`<section class="grid">${card('Shuttle devices','Loading…')}${card('Active exceptions','Loading…')}${card('Task exceptions','Loading…')}${card('System status','Read-only')}</section><section class="panel"><h2>Safety boundary</h2><p class="notice">This reconstruction calls only monitoring endpoints. Recovery, restart, task start/cancel, PLC write, and map-change routes remain documented but are not exposed here.</p></section>`;if(!token)return;try{const [devices,exceptions,count]=await Promise.all([request(api.monitor.devices,{token}),request(api.monitor.exceptions,{token}),request(api.monitor.taskCount,{token})]);const d=value(devices,['rows','data'],[]),e=value(exceptions,['rows','data'],[]);content.querySelector('.grid').innerHTML=card('Shuttle devices',Array.isArray(d)?d.length:'—','Recovered monitor API')+card('Active exceptions',Array.isArray(e)?e.length:'—','Recovered monitor API')+card('Task exceptions',value(count,['data','count']),'Recovered monitor API')+card('System status','Connected','Monitoring only');}catch(err){content.insertAdjacentHTML('beforeend',`<section class="panel notice">Unable to load monitor data: ${err.message}</section>`)} }
function settings(){content.innerHTML=`<section class="panel"><h2>Connect to ECS</h2><p class="label">Enter an existing ECS login token. It stays only in this browser session.</p><input id="token" type="password" placeholder="Bearer token" value="${token}"><button class="primary" id="save">Save connection</button></section>`;document.querySelector('#save').onclick=()=>{token=document.querySelector('#token').value.trim();token?sessionStorage.setItem('ecs-token',token):sessionStorage.removeItem('ecs-token');render('overview')}}
function placeholder(name,endpoint){content.innerHTML=`<section class="panel"><h2>${name}</h2><p class="empty">Read-only implementation pending. Contract endpoint: <code>${endpoint}</code></p><p class="notice">No physical equipment command is implemented in this baseline.</p></section>`}
function render(view){title.textContent=labels[view];document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===view));connection.textContent=token?'Token configured':'Not connected';connection.classList.toggle('live',Boolean(token));if(view==='overview')overview();else if(view==='settings')settings();else if(view==='devices')placeholder('Shuttle device inventory',api.device.list);else if(view==='tasks')placeholder('Task queue',api.task.list);else placeholder('Alert monitor',api.warning.list)}
document.querySelectorAll('.nav').forEach(x=>x.onclick=()=>render(x.dataset.view));render('overview');
